Add codeowners file
android/health-samples pull request #309
Opened 2024-10-22 18:28 UTC by breanatate

2024-10-24 00:24 UTC, bradoutlaw requested changes
boutlaw -> bradoutlaw to resolve errors

2024-10-24 08:04 UTC, yschimke commented on .github/CODEOWNERS
> +/health-services/ @breanatate @yschimke
I'm not sure I should be a CODEOWNER here.

I'm mainly helping out occasionally.

2024-10-24 08:05 UTC, yschimke commented
Should this affect how we approach renovate dependency updates?

https://github.com/android/health-samples/pull/307/files

I've been following the Wear samples guides for updates, but maybe we want those split out if possible along these project lines?

2024-10-24 14:57 UTC, breanatate commented
> Should this affect how we approach renovate dependency updates?
> 
> https://github.com/android/health-samples/pull/307/files
> 
> I've been following the Wear samples guides for updates, but maybe we want those split out if possible along these project lines?

Yes, I think this does affect that. I think the bulk of the HC/HP sample updates so far have been renovate-bot changes. And if we kept the CODEOWNERS file as is, I think it would mean that someone from HC would be required to also approve any renovate bot PRs.

2024-10-24 15:05 UTC, breanatate commented
If I move renovate.json into the health-services folder does that solve things?

2024-10-24 15:38 UTC, yschimke commented
> If I move renovate.json into the health-services folder does that solve things?

Let me check.

2024-11-01 19:26 UTC, breanatate commented
> > If I move renovate.json into the health-services folder does that solve things?
> 
> Let me check. But no need to block this PR.

I somehow missed the second sentence 🤦🏾 

I think [includePaths](https://docs.renovatebot.com/configuration-options/#includepaths) does what we need

2024-11-01 19:27 UTC, breanatate commented on .github/CODEOWNERS
> +/health-connect/ @abozowski @boutlaw @jessi3py
Sorry, I missed this! I'll send you a ping about getting added as a maintainer

2024-11-01 20:50 UTC, yschimke commented
Well this is a better outcome

2024-11-04 14:32 UTC, merged